apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pvxs-lab.fullname" . }}-gateway-conf
  labels:
    {{- include "pvxs-lab.labels" . | nindent 4 }}
data:
  gateway.conf: |-
  {{ tpl .Values.gateway.config . | nindent 4 }}
